### PR TITLE
show the output

### PR DESCRIPTION
**Pull request by runephilosof**
Personally I like it better when I see the output.

It should probably be an option.

### CODE REVIEW

**Comment by brysgo** [comment]
Since this gets run automatically a lot, I would rather see it be an option, as much as it is nice to see what is going on sometimes.

**Comment by bostrom** [comment]
I'd have to agree with @runephilosof since if this was done manually using ```rake db:migrate``` and ```rake db:rollback``` you would also see the output. I'd rather make it silent when needed using a ```--quiet``` option.

**Comment by brysgo** [comment]
@runephilosof @bostrom If one of you guys wants to maintain this feel free, I'm not spending most of my time in rails so I haven't put any effort into this.

**Comment by bostrom** [comment]
@brysgo I could give it a shot. Do you wish to transfer the original repo to a new owner or how do you want to delegate the maintenance?

**Comment by bostrom** [comment]
@brysgo @runephilosof this goes a little off topic, but have you guys checked out https://github.com/tpope/hookup which seems to solve the same issues as git-rails? Anything git-rails does (better) that hookup doesn't?

**Comment by brysgo** [comment]
@bostrom - Came up last year in a conversation I had with tpope. They are decidedly different, each having benefits and drawbacks. I've stuck with git rails mostly because it hasn't gotten in my way. If you have better success with hookup if love to hear what did it for you.

**Comment by brysgo** [comment]
@bostrom @runephilosof - would one of you like to maintain `git-rails` or have you switched to tpope/hookup?

**Comment by runephilosof** [comment]
Closed with opt in option in
aafd7570baf9c83149eb70fc46814ec27efba9be

**Pull request closed without merging**
